(import (prefix (ewmh) ewmh.)
        (globals)
        (prefix (wm) wm.)
        (prefix (icccm) icccm.)
        (prefix (shell) sh.)
        (xlib)
        (prefix (xutil) xutil.)
        (rnrs base))

(current-display (xutil.open))
(root (XDefaultRootWindow (current-display)))

(icccm.init-atoms)
(ewmh.init-atoms)
(wm.init-atoms)
